on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  releases-linux:
    name: Release Go Binary for Linux
    runs-on: linux-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      goos: linux
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build
        run: go build -o zenv-${{ github.event.release.tag_name }}-${{ github.env.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ github.env.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: zenv-${{ github.event.release.tag_name }}-${{ github.env.goos }}-${{ matrix.goarch }}

  releases-macos:
    name: Release Go Binary for MacOS
    runs-on: macos-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Build
        run: go build -o zenv-${{ github.event.release.tag_name }}-${{ github.env.goos }}-${{ matrix.goarch }}
        env:
          GOOS: ${{ github.env.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: zenv-${{ github.event.release.tag_name }}-${{ github.env.goos }}-${{ matrix.goarch }}
